# Generated by Django 4.0.1 on 2022-01-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='p_sim',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='s_sim',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='DeviceManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin1.customer')),
            ],
        ),
    ]
